spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.frp.contracts.events

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring.json.add.type.headers: false

    datasource:
      url: jdbc:postgresql://localhost:5433/orderdb?options=-c%20TimeZone=UTC
      username: orderuser
      password: orderpass
      driver-class-name: org.postgresql.Driver

      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update